/*
OpenAlex API

An OpenAPI specification for the OpenAlex API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListWorks200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWorks200Response{}

// ListWorks200Response struct for ListWorks200Response
type ListWorks200Response struct {
	Meta *ListWorks200ResponseMeta `json:"meta,omitempty"`
	Results []ListWorks200ResponseResultsInner `json:"results,omitempty"`
}

// NewListWorks200Response instantiates a new ListWorks200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWorks200Response() *ListWorks200Response {
	this := ListWorks200Response{}
	return &this
}

// NewListWorks200ResponseWithDefaults instantiates a new ListWorks200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWorks200ResponseWithDefaults() *ListWorks200Response {
	this := ListWorks200Response{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ListWorks200Response) GetMeta() ListWorks200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ListWorks200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorks200Response) GetMetaOk() (*ListWorks200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ListWorks200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ListWorks200ResponseMeta and assigns it to the Meta field.
func (o *ListWorks200Response) SetMeta(v ListWorks200ResponseMeta) {
	o.Meta = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *ListWorks200Response) GetResults() []ListWorks200ResponseResultsInner {
	if o == nil || IsNil(o.Results) {
		var ret []ListWorks200ResponseResultsInner
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorks200Response) GetResultsOk() ([]ListWorks200ResponseResultsInner, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ListWorks200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ListWorks200ResponseResultsInner and assigns it to the Results field.
func (o *ListWorks200Response) SetResults(v []ListWorks200ResponseResultsInner) {
	o.Results = v
}

func (o ListWorks200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWorks200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableListWorks200Response struct {
	value *ListWorks200Response
	isSet bool
}

func (v NullableListWorks200Response) Get() *ListWorks200Response {
	return v.value
}

func (v *NullableListWorks200Response) Set(val *ListWorks200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListWorks200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListWorks200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWorks200Response(val *ListWorks200Response) *NullableListWorks200Response {
	return &NullableListWorks200Response{value: val, isSet: true}
}

func (v NullableListWorks200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWorks200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


