/*
OpenAlex API

An OpenAPI specification for the OpenAlex API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AutocompleteEntities400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutocompleteEntities400Response{}

// AutocompleteEntities400Response struct for AutocompleteEntities400Response
type AutocompleteEntities400Response struct {
	// Error message describing the bad request
	Error *string `json:"error,omitempty"`
}

// NewAutocompleteEntities400Response instantiates a new AutocompleteEntities400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutocompleteEntities400Response() *AutocompleteEntities400Response {
	this := AutocompleteEntities400Response{}
	return &this
}

// NewAutocompleteEntities400ResponseWithDefaults instantiates a new AutocompleteEntities400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutocompleteEntities400ResponseWithDefaults() *AutocompleteEntities400Response {
	this := AutocompleteEntities400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *AutocompleteEntities400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutocompleteEntities400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *AutocompleteEntities400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *AutocompleteEntities400Response) SetError(v string) {
	o.Error = &v
}

func (o AutocompleteEntities400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutocompleteEntities400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableAutocompleteEntities400Response struct {
	value *AutocompleteEntities400Response
	isSet bool
}

func (v NullableAutocompleteEntities400Response) Get() *AutocompleteEntities400Response {
	return v.value
}

func (v *NullableAutocompleteEntities400Response) Set(val *AutocompleteEntities400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAutocompleteEntities400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAutocompleteEntities400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutocompleteEntities400Response(val *AutocompleteEntities400Response) *NullableAutocompleteEntities400Response {
	return &NullableAutocompleteEntities400Response{value: val, isSet: true}
}

func (v NullableAutocompleteEntities400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutocompleteEntities400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


