/*
OpenAlex API

An OpenAPI specification for the OpenAlex API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListWorks200ResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWorks200ResponseMeta{}

// ListWorks200ResponseMeta struct for ListWorks200ResponseMeta
type ListWorks200ResponseMeta struct {
	// Total number of results
	Count *int32 `json:"count,omitempty"`
	// Database response time in milliseconds
	DbResponseTimeMs *int32 `json:"db_response_time_ms,omitempty"`
	// Current page number
	Page *int32 `json:"page,omitempty"`
	// Number of results per page
	PerPage *int32 `json:"per_page,omitempty"`
	// Number of new results since last update
	CountNew *int32 `json:"count_new,omitempty"`
	// Number of updated results since last update
	CountUpdated *int32 `json:"count_updated,omitempty"`
}

// NewListWorks200ResponseMeta instantiates a new ListWorks200ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWorks200ResponseMeta() *ListWorks200ResponseMeta {
	this := ListWorks200ResponseMeta{}
	return &this
}

// NewListWorks200ResponseMetaWithDefaults instantiates a new ListWorks200ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWorks200ResponseMetaWithDefaults() *ListWorks200ResponseMeta {
	this := ListWorks200ResponseMeta{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ListWorks200ResponseMeta) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorks200ResponseMeta) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ListWorks200ResponseMeta) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ListWorks200ResponseMeta) SetCount(v int32) {
	o.Count = &v
}

// GetDbResponseTimeMs returns the DbResponseTimeMs field value if set, zero value otherwise.
func (o *ListWorks200ResponseMeta) GetDbResponseTimeMs() int32 {
	if o == nil || IsNil(o.DbResponseTimeMs) {
		var ret int32
		return ret
	}
	return *o.DbResponseTimeMs
}

// GetDbResponseTimeMsOk returns a tuple with the DbResponseTimeMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorks200ResponseMeta) GetDbResponseTimeMsOk() (*int32, bool) {
	if o == nil || IsNil(o.DbResponseTimeMs) {
		return nil, false
	}
	return o.DbResponseTimeMs, true
}

// HasDbResponseTimeMs returns a boolean if a field has been set.
func (o *ListWorks200ResponseMeta) HasDbResponseTimeMs() bool {
	if o != nil && !IsNil(o.DbResponseTimeMs) {
		return true
	}

	return false
}

// SetDbResponseTimeMs gets a reference to the given int32 and assigns it to the DbResponseTimeMs field.
func (o *ListWorks200ResponseMeta) SetDbResponseTimeMs(v int32) {
	o.DbResponseTimeMs = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ListWorks200ResponseMeta) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorks200ResponseMeta) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ListWorks200ResponseMeta) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *ListWorks200ResponseMeta) SetPage(v int32) {
	o.Page = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *ListWorks200ResponseMeta) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorks200ResponseMeta) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *ListWorks200ResponseMeta) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *ListWorks200ResponseMeta) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetCountNew returns the CountNew field value if set, zero value otherwise.
func (o *ListWorks200ResponseMeta) GetCountNew() int32 {
	if o == nil || IsNil(o.CountNew) {
		var ret int32
		return ret
	}
	return *o.CountNew
}

// GetCountNewOk returns a tuple with the CountNew field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorks200ResponseMeta) GetCountNewOk() (*int32, bool) {
	if o == nil || IsNil(o.CountNew) {
		return nil, false
	}
	return o.CountNew, true
}

// HasCountNew returns a boolean if a field has been set.
func (o *ListWorks200ResponseMeta) HasCountNew() bool {
	if o != nil && !IsNil(o.CountNew) {
		return true
	}

	return false
}

// SetCountNew gets a reference to the given int32 and assigns it to the CountNew field.
func (o *ListWorks200ResponseMeta) SetCountNew(v int32) {
	o.CountNew = &v
}

// GetCountUpdated returns the CountUpdated field value if set, zero value otherwise.
func (o *ListWorks200ResponseMeta) GetCountUpdated() int32 {
	if o == nil || IsNil(o.CountUpdated) {
		var ret int32
		return ret
	}
	return *o.CountUpdated
}

// GetCountUpdatedOk returns a tuple with the CountUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWorks200ResponseMeta) GetCountUpdatedOk() (*int32, bool) {
	if o == nil || IsNil(o.CountUpdated) {
		return nil, false
	}
	return o.CountUpdated, true
}

// HasCountUpdated returns a boolean if a field has been set.
func (o *ListWorks200ResponseMeta) HasCountUpdated() bool {
	if o != nil && !IsNil(o.CountUpdated) {
		return true
	}

	return false
}

// SetCountUpdated gets a reference to the given int32 and assigns it to the CountUpdated field.
func (o *ListWorks200ResponseMeta) SetCountUpdated(v int32) {
	o.CountUpdated = &v
}

func (o ListWorks200ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWorks200ResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.DbResponseTimeMs) {
		toSerialize["db_response_time_ms"] = o.DbResponseTimeMs
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.CountNew) {
		toSerialize["count_new"] = o.CountNew
	}
	if !IsNil(o.CountUpdated) {
		toSerialize["count_updated"] = o.CountUpdated
	}
	return toSerialize, nil
}

type NullableListWorks200ResponseMeta struct {
	value *ListWorks200ResponseMeta
	isSet bool
}

func (v NullableListWorks200ResponseMeta) Get() *ListWorks200ResponseMeta {
	return v.value
}

func (v *NullableListWorks200ResponseMeta) Set(val *ListWorks200ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableListWorks200ResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableListWorks200ResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWorks200ResponseMeta(val *ListWorks200ResponseMeta) *NullableListWorks200ResponseMeta {
	return &NullableListWorks200ResponseMeta{value: val, isSet: true}
}

func (v NullableListWorks200ResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWorks200ResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


