/*
OpenAlex API

An OpenAPI specification for the OpenAlex API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListAuthors200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAuthors200Response{}

// ListAuthors200Response struct for ListAuthors200Response
type ListAuthors200Response struct {
	Meta *ListAuthors200ResponseMeta `json:"meta,omitempty"`
	Results []ListAuthors200ResponseResultsInner `json:"results,omitempty"`
	GroupBy []ListAuthors200ResponseGroupByInner `json:"group_by,omitempty"`
}

// NewListAuthors200Response instantiates a new ListAuthors200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAuthors200Response() *ListAuthors200Response {
	this := ListAuthors200Response{}
	return &this
}

// NewListAuthors200ResponseWithDefaults instantiates a new ListAuthors200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAuthors200ResponseWithDefaults() *ListAuthors200Response {
	this := ListAuthors200Response{}
	return &this
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ListAuthors200Response) GetMeta() ListAuthors200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ListAuthors200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAuthors200Response) GetMetaOk() (*ListAuthors200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ListAuthors200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ListAuthors200ResponseMeta and assigns it to the Meta field.
func (o *ListAuthors200Response) SetMeta(v ListAuthors200ResponseMeta) {
	o.Meta = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *ListAuthors200Response) GetResults() []ListAuthors200ResponseResultsInner {
	if o == nil || IsNil(o.Results) {
		var ret []ListAuthors200ResponseResultsInner
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAuthors200Response) GetResultsOk() ([]ListAuthors200ResponseResultsInner, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ListAuthors200Response) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ListAuthors200ResponseResultsInner and assigns it to the Results field.
func (o *ListAuthors200Response) SetResults(v []ListAuthors200ResponseResultsInner) {
	o.Results = v
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *ListAuthors200Response) GetGroupBy() []ListAuthors200ResponseGroupByInner {
	if o == nil || IsNil(o.GroupBy) {
		var ret []ListAuthors200ResponseGroupByInner
		return ret
	}
	return o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAuthors200Response) GetGroupByOk() ([]ListAuthors200ResponseGroupByInner, bool) {
	if o == nil || IsNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *ListAuthors200Response) HasGroupBy() bool {
	if o != nil && !IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given []ListAuthors200ResponseGroupByInner and assigns it to the GroupBy field.
func (o *ListAuthors200Response) SetGroupBy(v []ListAuthors200ResponseGroupByInner) {
	o.GroupBy = v
}

func (o ListAuthors200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAuthors200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.GroupBy) {
		toSerialize["group_by"] = o.GroupBy
	}
	return toSerialize, nil
}

type NullableListAuthors200Response struct {
	value *ListAuthors200Response
	isSet bool
}

func (v NullableListAuthors200Response) Get() *ListAuthors200Response {
	return v.value
}

func (v *NullableListAuthors200Response) Set(val *ListAuthors200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAuthors200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAuthors200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAuthors200Response(val *ListAuthors200Response) *NullableListAuthors200Response {
	return &NullableListAuthors200Response{value: val, isSet: true}
}

func (v NullableListAuthors200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAuthors200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


