/*
OpenAlex API

An OpenAPI specification for the OpenAlex API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListAuthors200ResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAuthors200ResponseMeta{}

// ListAuthors200ResponseMeta Metadata about the API response
type ListAuthors200ResponseMeta struct {
	// The total number of entities (this will be all entities if no filter is applied)
	Count *int32 `json:"count,omitempty"`
	// The time taken by the database to respond, in milliseconds
	DbResponseTimeMs *int32 `json:"db_response_time_ms,omitempty"`
	// The current page number
	Page *int32 `json:"page,omitempty"`
	// The number of results per page
	PerPage *int32 `json:"per_page,omitempty"`
	// The count of groups in the current page (null if there are no groups in the response)
	GroupsCount NullableInt32 `json:"groups_count,omitempty"`
}

// NewListAuthors200ResponseMeta instantiates a new ListAuthors200ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAuthors200ResponseMeta() *ListAuthors200ResponseMeta {
	this := ListAuthors200ResponseMeta{}
	return &this
}

// NewListAuthors200ResponseMetaWithDefaults instantiates a new ListAuthors200ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAuthors200ResponseMetaWithDefaults() *ListAuthors200ResponseMeta {
	this := ListAuthors200ResponseMeta{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ListAuthors200ResponseMeta) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAuthors200ResponseMeta) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ListAuthors200ResponseMeta) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ListAuthors200ResponseMeta) SetCount(v int32) {
	o.Count = &v
}

// GetDbResponseTimeMs returns the DbResponseTimeMs field value if set, zero value otherwise.
func (o *ListAuthors200ResponseMeta) GetDbResponseTimeMs() int32 {
	if o == nil || IsNil(o.DbResponseTimeMs) {
		var ret int32
		return ret
	}
	return *o.DbResponseTimeMs
}

// GetDbResponseTimeMsOk returns a tuple with the DbResponseTimeMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAuthors200ResponseMeta) GetDbResponseTimeMsOk() (*int32, bool) {
	if o == nil || IsNil(o.DbResponseTimeMs) {
		return nil, false
	}
	return o.DbResponseTimeMs, true
}

// HasDbResponseTimeMs returns a boolean if a field has been set.
func (o *ListAuthors200ResponseMeta) HasDbResponseTimeMs() bool {
	if o != nil && !IsNil(o.DbResponseTimeMs) {
		return true
	}

	return false
}

// SetDbResponseTimeMs gets a reference to the given int32 and assigns it to the DbResponseTimeMs field.
func (o *ListAuthors200ResponseMeta) SetDbResponseTimeMs(v int32) {
	o.DbResponseTimeMs = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ListAuthors200ResponseMeta) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAuthors200ResponseMeta) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ListAuthors200ResponseMeta) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *ListAuthors200ResponseMeta) SetPage(v int32) {
	o.Page = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *ListAuthors200ResponseMeta) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAuthors200ResponseMeta) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *ListAuthors200ResponseMeta) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *ListAuthors200ResponseMeta) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetGroupsCount returns the GroupsCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListAuthors200ResponseMeta) GetGroupsCount() int32 {
	if o == nil || IsNil(o.GroupsCount.Get()) {
		var ret int32
		return ret
	}
	return *o.GroupsCount.Get()
}

// GetGroupsCountOk returns a tuple with the GroupsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAuthors200ResponseMeta) GetGroupsCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GroupsCount.Get(), o.GroupsCount.IsSet()
}

// HasGroupsCount returns a boolean if a field has been set.
func (o *ListAuthors200ResponseMeta) HasGroupsCount() bool {
	if o != nil && o.GroupsCount.IsSet() {
		return true
	}

	return false
}

// SetGroupsCount gets a reference to the given NullableInt32 and assigns it to the GroupsCount field.
func (o *ListAuthors200ResponseMeta) SetGroupsCount(v int32) {
	o.GroupsCount.Set(&v)
}
// SetGroupsCountNil sets the value for GroupsCount to be an explicit nil
func (o *ListAuthors200ResponseMeta) SetGroupsCountNil() {
	o.GroupsCount.Set(nil)
}

// UnsetGroupsCount ensures that no value is present for GroupsCount, not even an explicit nil
func (o *ListAuthors200ResponseMeta) UnsetGroupsCount() {
	o.GroupsCount.Unset()
}

func (o ListAuthors200ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAuthors200ResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.DbResponseTimeMs) {
		toSerialize["db_response_time_ms"] = o.DbResponseTimeMs
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if o.GroupsCount.IsSet() {
		toSerialize["groups_count"] = o.GroupsCount.Get()
	}
	return toSerialize, nil
}

type NullableListAuthors200ResponseMeta struct {
	value *ListAuthors200ResponseMeta
	isSet bool
}

func (v NullableListAuthors200ResponseMeta) Get() *ListAuthors200ResponseMeta {
	return v.value
}

func (v *NullableListAuthors200ResponseMeta) Set(val *ListAuthors200ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableListAuthors200ResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableListAuthors200ResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAuthors200ResponseMeta(val *ListAuthors200ResponseMeta) *NullableListAuthors200ResponseMeta {
	return &NullableListAuthors200ResponseMeta{value: val, isSet: true}
}

func (v NullableListAuthors200ResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAuthors200ResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


